// Generated by LiveScript 1.2.0
(function(){
  var piper;
  piper = require('../../../router/pipe/piper');
  describe('pipe and unpipe', function(){
    return specify('should pipe parse calls to multiple routers', function(){
      var r1, r2, r3, matches;
      r1 = crossroads.create();
      r2 = crossroads.create();
      r3 = crossroads.create();
      matches = [];
      r1.addRoute('{foo}', function(f){
        return matches.push('r1:' + f);
      });
      r2.addRoute('{foo}', function(f){
        return matches.push('r2:' + f);
      });
      r3.addRoute('bar', function(f){
        return matches.push('r3:' + f);
      });
      r1.pipe(r2);
      r1.pipe(r3);
      r1.parse('foo');
      r1.parse('bar');
      r1.unpipe(r2);
      r1.parse('dolor');
      return expect(matches).toEqual(['r1:foo', 'r2:foo', 'r1:bar', 'r2:bar', 'r3:undefined', 'r1:dolor']);
    });
  });
}).call(this);
