// Generated by LiveScript 1.2.0
(function(){
  var expect;
  expect = require('chai').expect;
  describe('Utils', function(){
    return describe('arrayIndexOf', function(){
      return specify('works', function(){
        return expect(1).to.eql(1);
      });
    });
  });
}).call(this);
